# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6622b9ec20514b3b06a90c4331aea37f"
name = "PetFilter"
application_url = "https://etc-folding-challenged-criterion.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobjects,write_metaobjects,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "http://localhost:3000/auth", "https://acids-seeking-lover-stockholm.trycloudflare.com/auth" ]

[app_proxy]
url = "/proxy"
subpath = "pet-filter"
prefix = "apps"
