// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/proxy/compatible-count": {
    params: {};
  };
  "/proxy/best-matches": {
    params: {};
  };
  "/proxy/settings": {
    params: {};
  };
  "/webhooks/gdpr": {
    params: {};
  };
  "/proxy/badge": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/proxy/pets": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/onboarding": {
    params: {};
  };
  "/app/matching": {
    params: {};
  };
  "/app/products": {
    params: {};
  };
  "/app/settings": {
    params: {};
  };
  "/app/billing": {
    params: {};
  };
  "/app/billing/callback": {
    params: {};
  };
  "/app/rules": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/proxy/compatible-count" | "/proxy/best-matches" | "/proxy/settings" | "/webhooks/gdpr" | "/proxy/badge" | "/auth/login" | "/proxy/pets" | "/auth/*" | "/app" | "/app/onboarding" | "/app/matching" | "/app/products" | "/app/settings" | "/app/billing" | "/app/billing/callback" | "/app/rules";
  };
  "routes/webhooks.app.scopes_update.tsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.tsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/proxy.compatible-count.tsx": {
    id: "routes/proxy.compatible-count";
    page: "/proxy/compatible-count";
  };
  "routes/proxy.best-matches.tsx": {
    id: "routes/proxy.best-matches";
    page: "/proxy/best-matches";
  };
  "routes/proxy.settings.tsx": {
    id: "routes/proxy.settings";
    page: "/proxy/settings";
  };
  "routes/webhooks.gdpr.tsx": {
    id: "routes/webhooks.gdpr";
    page: "/webhooks/gdpr";
  };
  "routes/proxy.badge.tsx": {
    id: "routes/proxy.badge";
    page: "/proxy/badge";
  };
  "routes/auth.login/route.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/proxy.pets.tsx": {
    id: "routes/proxy.pets";
    page: "/proxy/pets";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/onboarding" | "/app/matching" | "/app/products" | "/app/settings" | "/app/billing" | "/app/billing/callback" | "/app/rules";
  };
  "routes/app.onboarding.tsx": {
    id: "routes/app.onboarding";
    page: "/app/onboarding";
  };
  "routes/app.matching.tsx": {
    id: "routes/app.matching";
    page: "/app/matching";
  };
  "routes/app.products.tsx": {
    id: "routes/app.products";
    page: "/app/products";
  };
  "routes/app.settings.tsx": {
    id: "routes/app.settings";
    page: "/app/settings";
  };
  "routes/app.billing.tsx": {
    id: "routes/app.billing";
    page: "/app/billing" | "/app/billing/callback";
  };
  "routes/app.billing.callback.tsx": {
    id: "routes/app.billing.callback";
    page: "/app/billing/callback";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.rules.tsx": {
    id: "routes/app.rules";
    page: "/app/rules";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.tsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.tsx");
  "routes/proxy.compatible-count": typeof import("./app/routes/proxy.compatible-count.tsx");
  "routes/proxy.best-matches": typeof import("./app/routes/proxy.best-matches.tsx");
  "routes/proxy.settings": typeof import("./app/routes/proxy.settings.tsx");
  "routes/webhooks.gdpr": typeof import("./app/routes/webhooks.gdpr.tsx");
  "routes/proxy.badge": typeof import("./app/routes/proxy.badge.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.tsx");
  "routes/proxy.pets": typeof import("./app/routes/proxy.pets.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.onboarding": typeof import("./app/routes/app.onboarding.tsx");
  "routes/app.matching": typeof import("./app/routes/app.matching.tsx");
  "routes/app.products": typeof import("./app/routes/app.products.tsx");
  "routes/app.settings": typeof import("./app/routes/app.settings.tsx");
  "routes/app.billing": typeof import("./app/routes/app.billing.tsx");
  "routes/app.billing.callback": typeof import("./app/routes/app.billing.callback.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
  "routes/app.rules": typeof import("./app/routes/app.rules.tsx");
};